log:
  level: debug
  disable_sentry: true

db:
  url: url

horizon:
  url: url

listener:
  addr: :3000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: blob-storage
  service_port: 80
