// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "b3ea633ad296380d7cebac6c67fda319"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"ca71285196e32e1f7b766c17e610ab5c": "1f8b08000000000000ff9c92414f83401484effc8a3996688f7ae1542d2a49434da1b137b2c0b3ddb8ec92b74bb1fe7a53b655693c18afcccb3733cc4ea7b86ae4968523acdb20b85fc5b33c463ebb5bc4e82cb1c524000059a3945b4b2c8542cbb2117cc01b1dae075599add4d80bae76822737b721d2658e74bd5878bd15d6f6866b387a77175ac5241cd5857070b221eb44d3a2976e673aff051f4653104617e94a65cabfa5db0bd5d1ffadfdade93571e18da476d0c641774a81e995987445f6fcc3641dc268d4a4c8112a612b518f0a24e93cdef80285e756465bc7e2085ea6a76aeb2c491f513a26c2e46c1fe2e5295ec5df7192ecab5434e61fd314c33217781f73841fcece6cbfe6081cfc7c2873d3eb2098af96cfa7299207c49b24cb339f3cfa5d1b6ca3cf000000ffffcae0394372020000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "ca71285196e32e1f7b766c17e610ab5c"})
	}()
	return nil
}()
